packages:
  - packages/*

catalog:
  '@changesets/cli': ^2.29.7
  '@eslint/js': ^9.38.0
  '@koa/bodyparser': ^6.0.0
  '@koa/router': ^14.0.0
  '@types/koa': 2.15.0
  '@types/koa__router': ^12.0.4
  '@types/node': ^22.18.11
  '@types/supertest': 6.0.3
  '@typescript-eslint/eslint-plugin': ^8.46.1
  '@typescript-eslint/parser': ^8.46.1
  bson: ^6.2.0
  class-transformer: ^0.5.1
  class-transformer-validator: ^0.9.1
  class-validator: ^0.14.0
  eslint: ^9.38.0
  express: ^5.1.0
  koa: ^3.0.2
  lerna: ^8.2.4
  prettier: ^3.6.2
  reflect-metadata: 0.2.2
  supertest: ^7.1.4
  ts-node: ^10.9.2
  typescript: ^5.9.3
  typescript-eslint: ^8.46.1
  vitepress: ^1.6.4
  vitest: 2.1.9

catalogMode: prefer

onlyBuiltDependencies:
  - esbuild
  - nx
