name: CI

env:
  CI: true

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Lint on Node.js
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm lint

  build:
    runs-on: ubuntu-latest
    name: Build on Node.js
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Building
        run: pnpm build

      - name: Cache dist
        uses: actions/cache@v4
        with:
          path: dist
          key: node-v20-${{ github.sha }}

  test:
    needs:
      - build
    runs-on: ubuntu-latest

    name: Test on Node.js
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore dist cache
        uses: actions/cache@v4
        with:
          path: dist
          key: node-v20-${{ github.sha }}

      - name: Testing
        run: pnpm test
